export const INITIAL_CATEGORIES = [
  { id: '1', name: 'Barbería',     iconName: 'Scissors'     },
  { id: '2', name: 'Electricidad', iconName: 'Zap'          },
  { id: '3', name: 'Odontología',  iconName: 'Activity'     },
  { id: '4', name: 'Limpieza',     iconName: 'Sparkles'     },
  { id: '5', name: 'Masajes',      iconName: 'Smile'        },
  { id: '6', name: 'Tutoría',      iconName: 'GraduationCap'},
  { id: '7', name: 'Fisioterapia', iconName: 'HeartPulse'   },
];

const DEFAULT_HOURS = [
  { day: 'Lunes',     enabled: true,  start: '09:00', end: '18:00' },
  { day: 'Martes',    enabled: true,  start: '09:00', end: '18:00' },
  { day: 'Miércoles', enabled: true,  start: '09:00', end: '18:00' },
  { day: 'Jueves',    enabled: true,  start: '09:00', end: '18:00' },
  { day: 'Viernes',   enabled: true,  start: '09:00', end: '18:00' },
  { day: 'Sábado',    enabled: true,  start: '10:00', end: '14:00' },
  { day: 'Domingo',   enabled: false, start: '09:00', end: '18:00' },
];

export const INITIAL_PROFESSIONALS = [
  {
    id: 'p1',
    name: 'Dr. Alejandro Rossi',
    email: 'alejandro.rossi@email.com',
    password: '123456',
    phone: '+34 666 555 111',
    category: 'Fisioterapia',
    description: 'Especialista en rehabilitación deportiva y terapia manual con más de 10 años de experiencia ayudando a atletas a recuperar su máximo rendimiento.',
    rating: 4.9,
    status: 'activo',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=256&h=256',
    clinicImage: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&q=80&w=1000',
    services: [
      { id: 's1', name: 'Consulta Inicial',       durationMin: 60, price: 90  },
      { id: 's2', name: 'Terapia Manual',          durationMin: 45, price: 75  },
      { id: 's3', name: 'Evaluación de Lesión',    durationMin: 60, price: 85  },
      { id: 's4', name: 'Plan de Rehabilitación',  durationMin: 90, price: 120 },
    ],
    hours: DEFAULT_HOURS,
  },
  {
    id: 'p2',
    name: 'Alejandro Gómez',
    email: 'alejandro.gomez@email.com',
    password: '123456',
    phone: '+34 666 555 222',
    category: 'Barbería',
    description: 'Estilista profesional de barbería clásica y moderna. Diseños de barba, afeitado tradicional con navaja y cortes en tendencia.',
    rating: 4.8,
    status: 'activo',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256&h=256',
    services: [
      { id: 's5', name: 'Corte de Pelo (Hombre)', durationMin: 30, price: 25 },
      { id: 's6', name: 'Tinte y Mechas',          durationMin: 90, price: 80 },
      { id: 's7', name: 'Corte y Peinado',         durationMin: 60, price: 50 },
    ],
    hours: DEFAULT_HOURS,
  },
  {
    id: 'p3',
    name: 'Mariana Silva',
    email: 'mariana.silva@email.com',
    password: '123456',
    phone: '+34 666 555 333',
    category: 'Electricidad',
    description: 'Electricista autorizada para instalaciones residenciales y comerciales. Solución rápida de averías, boletines eléctricos y luminarias.',
    rating: 4.8,
    status: 'activo',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=256&h=256',
    services: [
      { id: 's8',  name: 'Instalación de Luminarias',   durationMin: 45, price: 40 },
      { id: 's9',  name: 'Reparación de Cortocircuito', durationMin: 60, price: 60 },
      { id: 's10', name: 'Revisión Eléctrica General',  durationMin: 90, price: 80 },
    ],
    hours: DEFAULT_HOURS,
  },
  {
    id: 'p4',
    name: 'Calana Honez',
    email: 'calana.honez@email.com',
    password: '123456',
    phone: '+34 666 555 444',
    category: 'Barbería',
    description: 'Especialista en cortes de caballero clásicos y barbas perfiladas. Atención personalizada con productos premium.',
    rating: 4.8,
    status: 'activo',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256&h=256',
    services: [
      { id: 's11', name: 'Corte Clásico',     durationMin: 30, price: 20 },
      { id: 's12', name: 'Perfilado de Barba', durationMin: 20, price: 12 },
    ],
    hours: DEFAULT_HOURS,
  },
  {
    id: 'p5',
    name: 'Luman Seviner',
    email: 'luman.seviner@email.com',
    password: '123456',
    phone: '+34 666 555 555',
    category: 'Electricidad',
    description: 'Servicio técnico eléctrico de urgencias y reformas generales. Amplio recorrido en reparación de cuadros y cableado.',
    rating: 4.8,
    status: 'activo',
    avatar: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?auto=format&fit=crop&q=80&w=256&h=256',
    services: [
      { id: 's13', name: 'Instalación Interruptores', durationMin: 30, price: 30 },
      { id: 's14', name: 'Diagnóstico Cableado',       durationMin: 60, price: 50 },
    ],
    hours: DEFAULT_HOURS,
  },
  {
    id: 'p6',
    name: 'Danielsa Gómez',
    email: 'danielsa.gomez@email.com',
    password: '123456',
    phone: '+34 666 555 666',
    category: 'Odontología',
    description: 'Clínica odontológica con tecnología de punta. Servicios de limpieza profunda, blanqueamiento, ortodoncia y diseño de sonrisa.',
    rating: 4.8,
    status: 'activo',
    avatar: 'https://images.unsplash.com/photo-1594824813573-246434e33963?auto=format&fit=crop&q=80&w=256&h=256',
    services: [
      { id: 's15', name: 'Limpieza Dental',       durationMin: 45, price: 45 },
      { id: 's16', name: 'Consulta y Diagnóstico', durationMin: 30, price: 30 },
    ],
    hours: DEFAULT_HOURS,
  },
  {
    id: 'p7',
    name: 'Ana García',
    email: 'ana.garcia@email.com',
    password: '123456',
    phone: '+34 666 555 777',
    category: 'Odontología',
    description: 'Dentista integral enfocada en tratamientos preventivos y restauradores para toda la familia.',
    rating: 4.7,
    status: 'pendiente',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=256&h=256',
    services: [
      { id: 's17', name: 'Tratamiento de Caries', durationMin: 60, price: 55 },
    ],
    hours: DEFAULT_HOURS,
  },
  {
    id: 'p8',
    name: 'Carlos López',
    email: 'carlos.lopez@email.com',
    password: '123456',
    phone: '+34 666 555 888',
    category: 'Fisioterapia',
    description: 'Fisioterapeuta deportivo con enfoque en terapia neuromuscular avanzada.',
    rating: 4.8,
    status: 'activo',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=256&h=256',
    services: [
      { id: 's18', name: 'Sesión Fisioterapia Deportiva', durationMin: 50, price: 70 },
    ],
    hours: DEFAULT_HOURS,
  },
  {
    id: 'p9',
    name: 'Elena Ruiz',
    email: 'elena.ruiz@email.com',
    password: '123456',
    phone: '+34 666 555 999',
    category: 'Tutoría',
    description: 'Nutricionista clínica y asesora de bienestar saludable.',
    rating: 4.5,
    status: 'bloqueado',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=256&h=256',
    services: [
      { id: 's19', name: 'Consulta Nutricional Inicial', durationMin: 45, price: 50 },
    ],
    hours: DEFAULT_HOURS,
  },
];

export const INITIAL_BOOKINGS = [
  {
    id: 'UUID-1245',
    professionalId: 'p2',
    professionalName: 'Alejandro Gómez',
    serviceId: 's7',
    serviceName: 'Corte y Peinado',
    price: 50,
    date: '2026-06-28',
    time: '10:00',
    clientName: 'Ana Graveno',
    clientPhone: '(666) 555-444',
    status: 'pendiente',
  },
  {
    id: 'UUID-1246',
    professionalId: 'p2',
    professionalName: 'Alejandro Gómez',
    serviceId: 's6',
    serviceName: 'Tinte y Mechas',
    price: 80,
    date: '2026-06-28',
    time: '13:30',
    clientName: 'Ana Mariana',
    clientPhone: '(616) 337-444',
    status: 'pendiente',
  },
  {
    id: 'UUID-1247',
    professionalId: 'p2',
    professionalName: 'Alejandro Gómez',
    serviceId: 's5',
    serviceName: 'Corte de Pelo (Hombre)',
    price: 25,
    date: '2026-06-29',
    time: '09:00',
    clientName: 'Ana G.',
    clientPhone: '666 555 444',
    status: 'confirmada',
  },
];
